hashicorp/packer-plugin-ansible

- example/docker-ansible-local.pkr.hcl
- example/local-playbook.yml
- main.go
Before change
```
Error: Unknown provisioner type "ansible-local"
2021/05/11 10:43:56 [INFO] (telemetry) Finalizing.
on ansible_local_docker.pkr.hcl line 17:
(source code not available)
known provisioners: [ansible-ansible-local azure-azure-dtlartifact breakpoint
shell puppet-puppet-masterless scaffolding scaffolding-ansible-local ansible
chef-client powershell windows-shell sleep chef-chef-client chef-chef-solo
converge windows-restart shell-local puppet-masterless file puppet-server
chef-solo puppet-puppet-server salt-masterless azure-dtlartifact inspec]
```
After changes
```
docker.example: Executing Ansible: cd /tmp/packer-provisioner-ansible-local/609a99da-7d63-d70b-6761-21607d741553 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook …
```
> Fix `ansible-local` plugin registration

- .gitignore
- go.mod
This changes marks the referenced versions as unusable. The retract directive does not prevent the versions from being used but it will notify consumers that the version has been marked as unusable and encourage the consumer to upgrade. 
Current available versions
```
~>  go list -versions -m github.com/hashicorp/packer-plugin-ansible
github.com/hashicorp/packer-plugin-ansible v0.0.1 v0.0.2 v0.0.3
```
Once merged listing available version should look something like
```
~>  go list -versions -m github.com/hashicorp/packer-plugin-ansible
github.com/hashicorp/packer-plugin-ansible v0.0.3
```
> Add go mod retractions for versions: v0.0.1, v0.0.2

- docs/provisioners/ansible-local.mdx
`ansible-local` provider documentation is showing `ansible` provider configuration attributes instead of `ansible-local` ones.
> Fix documentation for ansible-local provider

- docs-partials/provisioner/ansible-local/Config-not-required.mdx
- docs-partials/provisioner/ansible/Config-not-required.mdx
- provisioner/ansible-local/provisioner.go
- provisioner/ansible/provisioner.go
WinRMPassword is deprecated in favor of `${build.Password}` and {{build `Password`}}
Fixes #56
> update ansible docs to remove references to WinRMPassword 

- docs/provisioners/ansible.mdx
Fix a minimal typo in the documentation.
> docs: Fix small typo

- docs-partials/provisioner/ansible/Config-not-required.mdx
- provisioner/ansible/provisioner.go
With the move to developer.hashicorp.com some links between the general doc and plugins were broken. This PR fixes them
> docs: fix references to internal documentation

- docs/provisioners/ansible-local.mdx
The last PR forgot to update a link for the new dev site, this PR fixes this.
> docs: fix link to packer docs

- docs/provisioners/ansible.mdx
updating docs to reflect the correct parameter name and where it should be set
should be `use_proxy`, not `set_proxy` 
resolves: https://github.com/hashicorp/packer-plugin-ansible/issues/148
> docs: fix typo in parameter name for troubleshooting section

- docs/provisioners/ansible.mdx
Adding more examples to the Ansible-remote provisioner. The current example is only working for AWS and not Azure.
The username "Administrator" does not work in Azure. The example in this PR works for Azure Server 2019 using Ansible Remote.
> Adding example of using azure-arm and WinRm

- .goreleaser.yml
This hopefully results in illumos binaries being made available, currently the experience is:
```shell
$ packer init -upgrade .
Failed getting the "github.com/hashicorp/ansible" plugin:
15 errors occurred:
* ignoring invalid remote binary packer-plugin-ansible_v1.0.3_x5.0_freebsd_arm64.zip: wrong system, expected illumos_amd64 
[...]
* could not install any compatible version of plugin "github.com/hashicorp/ansible"
```
Many thanks.
> Build plugin for illumos.

- provisioner/ansible/provisioner.go
Hi,
When passing more than one ssh extra arg, they are concatenated without a space between them.
Using strings.Join fixes the issue.
Closes #116
> Fix missing space between ssh extra args

- docs/provisioners/ansible.mdx
In the documentation for the remote ansible provisioner, a misconstructed Tabs was added in between release v1.0.3 and v1.0.4.
In effect, this prevented the documentation from being generated again, and made previewing docs impossible on Packer.
This commit removes the mismatched Tabs since there's only an HCL2 template specified, therefore there's no need for Tabs here.
> docs: remove misconstructed tabs

- docs-partials/provisioner/ansible/Config-not-required.mdx
- provisioner/ansible/provisioner.go
- provisioner/ansible/provisioner.hcl2spec.go
When using RSA keys, for some obscure reason, the SSH connection only accepts rsa-sha1 as the signature algorithm for the key, which is now unsupported in modern OpenSSH versions.
This causes problems when using Ansible in conjunction with the proxy adapter (the default), as Ansible uses `ssh' to connect, and in turn, rejects the connection unless users manually change their config to support this, or if they add extra options to Ansible in their templates to accept these insecure methods.
To fix this, we move to ECDSA keys for the Ansible adapter. We considered using ED25519, but these keys are only supported by SSH when using the native serialisation format, and not any of the PKCS variants, making it harder to serialise as we'd need to write our own serialisation method for this …
> adapter: use ECDSA keys for adapter instead of RSA

- README.md
- version/version.go
This is a minor bump because of the change from RSA to ECDSA for the adapter SSH keys we generate. This will likely be harmless for most users, but given that it might break some configs in legacy environments, we opt to minor bump this time.
> Release 1.1.0

- docs-partials/provisioner/ansible/Config-not-required.mdx
Hello, the Config-not-required.mdx file had a bug in two code samples due to missing linebreaks.
> Fixed a bug in Config-not-required.mdx documentation

- provisioner/ansible/provisioner.go
- provisioner/ansible/provisioner_test.go
Fixes #158 by quoting individual arguments in the `ansible_ssh_extra_args` list instead of joining arguments and only quoting all of them together after.
Note that I kept the simple implementation of only putting arguments in quotes but ideally, you'd probably want to consider using a dedicated library for joining arguments using sh's word-splitting rules such as [go-shellquote](https://github.com/kballard/go-shellquote).
Recreated from #168 because I used the wrong account, sorry about the spam...
> Fix quoting of arguments passed through ansible_ssh_extra_args

- provisioner/ansible/provisioner.go
Handled the case where the Host IP isn't set in the case of builders like lxc, etc. 
This caused the plugin to crash with a panic. With this change the crash is handled. Issue reported in #204
> handle missing or invalid Host IP gracefully in provisioner

- docs/provisioners/ansible.mdx
**Description**: 
I am updating a broken link in the ansible plugin documentation
current link - https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
new link - https://github.com/ansible/ansible-documentation/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
> Update ansible script link to configure remoting for ansible

- .github/workflows/build.yml
Removed the branch argument while calling the generate metadata.json file. The branch name in the output file comes out blank when this is passed.
> Fix branch name in metadata.json

- .github/workflows/build.yml
The api_version was not set as output of the plugin-check job which resulted in missing version in binary name.
> Fixed api_version not set in the binary name in artifacts

- .github/workflows/build.yml
Added a job to create and upload manifest.json file during build
This json file stores the API version used by the plugin since the api_version was stripped from the zip filename This helps in determining the right plugin version during installation
> Add manifest json file during build

- .github/workflows/build.yml
- .release/packer-plugin-ansible-artifacts.hcl
Remove illumos os from builds
Packer isn't released with illumos os type, hence
removing from plugins build
> Remove illumos os from builds
